name_filter = ['aj applegate',
               'alexis texas',
               'sophia leone',
               'alexis love',
               'nicole aniston',
               'ketty caprice',
               'aallyah hadid',
               'peter green',
               'monica santhiago',
               'abbey brooks',
               'zoey monroe',
               'persia paradise',
               'rose monroe',
               'crystal lust',
               'carmela clutch',
               'gabriela lopez',
               'penny pax',
               'lea lexis',
               'kitten latenight',
               'miss raquel',
               'azar dares',
               'mona azar',
               'sheena ryder',
               'jenna starr',
               'anikka albrite',
               'jayden jaymes',
               'ashlyn peaks',
               'mariah milano',
               'mandy muse',
               'isis love',
               'diamond kitty',
               'ryan keely',
               'romi rain',
               'violet myers',
               'culona mama vergas',
               'destiny dane',
               'alina belle',
               'ella knox',
               'ava rose',
               'jayden jaymes',
               'lilly hall',
               'kali roses',
               'diamond banks',
               'naomi russell',
               'kaila simone',
               'leana lovings'
               ]

